version: '3'

services:

  server:
    container_name: server
    image: server:1.0
    build: .
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:password@pg_database:5432/database
    depends_on:
      pg_database:
        condition: service_healthy

  pg_database:
    container_name: pg_database
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
  
volumes:
  pg_data:
    driver: local