name: Run linter

on:
  push:
    branches: [ "main" , "development" ]
  pull_request:
    branches: [ "main" , "development" ]

jobs:
  linter:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Instaling Dependencies
      run: npm install
    - name: Running Tests
      run: npx eslint .
